/* addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"              % "0.4.1") */
addSbtPlugin("org.scalameta"       % "sbt-scalafmt"      % "2.4.6")
addSbtPlugin("com.github.sbt"      % "sbt-ci-release"    % "1.5.10")
addSbtPlugin("ch.epfl.scala"       % "sbt-scalafix"      % "0.10.1")
addSbtPlugin("com.eed3si9n"        % "sbt-buildinfo"     % "0.10.0")
addSbtPlugin("com.eed3si9n"        % "sbt-projectmatrix" % "0.9.0")
addSbtPlugin("de.heikoseeberger"   % "sbt-header"        % "5.6.5")
addSbtPlugin("org.scala-js"        % "sbt-scalajs"       % "1.10.1")
addSbtPlugin("org.scala-native"    % "sbt-scala-native"  % "0.4.5")
addSbtPlugin("org.scalameta"       % "sbt-mdoc"          % "2.3.3")
addSbtPlugin("com.github.reibitto" % "sbt-welcome"       % "0.2.2")
